[package]
name = "folderify"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.1.8", features = ["derive"] }
command-fds = "0.2.2"
include_dir = "0.7.3"
mktemp = "0.5.0"
