[package]
name = "folderify"
version = "3.0.0-pre1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.1.8", features = ["derive"] }
include_dir = "0.7.3"
mktemp = "0.5.0"
