on: [push, pull_request]
name: Test on macOS
jobs:
  test:
    strategy:
      matrix:
        python-version: [2.7, 3.9]
        os: [macos-10.15, macos-11.0, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install ImageMagick
        run: brew install imagemagick
      - name: Generate icon files
        run: python -m folderify ./examples/src/apple.png
      - name: Check generated icon files.
        run: .github/workflows/check-generated-files.sh
      - name: Generate and assign folder icon
        run: python -m folderify ./examples/src/apple.png .
      - name: Check assigned icon.
        run: .github/workflows/check-assigned-icon.sh
